### ISSUE TITLE
HTTP headers add/strip policy is not working properly

### ISSUE THREAD

**Issue by FedeAmdan** [mulesoft/api-policies#2]
This policy does not work properly in GW 2.0 and the previous versions. It attempts to remove headers  (from the outbound properties map) as soon as they arrive to the app, but at that point: 
- The outbound properties map is empty
- All the headers are located in the inbound properties map, which can not be modified.

Regarding to the proxies, as the inbound properties are copied to the outbound properties map just before making the request to the implementation api, the unwanted headers are sent anyway.

**Comment by rusinm** [comment]
I observed that the request outbound properties map contained 'MULE_ENCODING' header in GW 1.3.2 so I left an option to remove headers there as was required by this policy specification. It's true in GW 2.0 the outbound properties map is empty and the map is overwritten though. Thanks for pointing out.

**Comment by rusinm** [comment]
The deleting headers feature in request outbound properties map was removed.
