### ISSUE TITLE
Web Service Security to Basic authentication transformation policy does not work in API Gateway 2.0

### ISSUE THREAD

**Issue by FedeAmdan** [mulesoft/api-policies#3]
The transformation policy is not working in API Gateway 2.0. because is assuming that the runtime is including the class org.jboss.netty.buffer.ChannelBufferInputStream, but it is not. The policy can be fixed by replacing the previous invocation with java.io.InputStream.

**Comment by rusinm** [comment]
Thanks for your comments. It was fixed.
